Repository redhat-best-practices-for-k8s/certsuite, pull requests merged in 2023-11, with the labels that each got.

#1594 Setup QE OCP 4.14 runner
  .github/workflows/qe-ocp-413-intrusive.yaml
  .github/workflows/qe-ocp-413.yaml
  .github/workflows/qe-ocp-414-intrusive.yaml
  .github/workflows/qe-ocp-414.yaml
Labels: work in progress

#1615 Dependency updates for ginkgo removal branch
  go.mod
  go.sum
Labels: Backport

#1614 Transition manageability suite to ginkgoless
  cnf-certification-test/manageability/suite.go
  generated_policy.json
  main.go
Labels: ginkgoless

#1625 Fix for the webserver kubeconfig file handling.
  cnf-certification-test/webserver/webserver.go
  internal/clientsholder/clientsholder.go
  main.go
Labels: ginkgoless

#1620 Transition performance suite to ginkgoless.
  cnf-certification-test/performance/suite.go
  generated_policy.json
  main.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1628 QE Test: Remove keep-going flag
  .github/workflows/qe-hosted.yml
  .github/workflows/qe-ocp-413-intrusive.yaml
  .github/workflows/qe-ocp-413.yaml
  .github/workflows/qe-ocp-414-intrusive.yaml
  .github/workflows/qe-ocp-414.yaml
  .github/workflows/qe.yaml
Labels: work in progress

#1622 Transition certification suite to ginkgoless.
  cnf-certification-test/certification/suite.go
  generated_policy.json
  main.go
  pkg/tnf/status.go
Labels: non backward compatible, ginkgoless

#1645 Allow more than one skip functions per check.
  cnf-certification-test/observability/suite.go
  pkg/checksdb/check.go
  pkg/checksdb/checksgroup.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1644 webserver: add implementation for uploading tnf config file and add all the fields
  cnf-certification-test/webserver/index.html
  cnf-certification-test/webserver/index.js
  cnf-certification-test/webserver/submit.js
  cnf-certification-test/webserver/webserver.go
Labels: ginkgoless

#1649 Reapplied PR #1642
  .github/actions/setup/action.yml
  .github/workflows/pre-main.yaml
  .github/workflows/qe-hosted.yml
  .github/workflows/qe-ocp-413-intrusive.yaml
  .github/workflows/qe-ocp-413.yaml
  .github/workflows/qe-ocp-414-intrusive.yaml
  .github/workflows/qe-ocp-414.yaml
  .github/workflows/qe.yaml
  .github/workflows/tnf-image.yaml
  Dockerfile
  cnf-certification-test/platform/operatingsystem/files/rhcos_version_map
  go.mod
  go.sum
  pkg/provider/isolation.go
  pkg/provider/isolation_test.go
Labels: ginkgoless

#1648 Reapplied PR #1622
  cnf-certification-test/certification/suite.go
  generated_policy.json
  main.go
  pkg/tnf/status.go
Labels: ginkgoless

#1616 Transition accesscontrol suite to ginkgoless
  cnf-certification-test/accesscontrol/suite.go
  generated_policy.json
  main.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1621 Transition networking suite to ginkgoless
  cnf-certification-test/networking/suite.go
  main.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1627 Transition lifecycle suite to ginkgoless
  cnf-certification-test/lifecycle/suite.go
  main.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1655 Lifecycle ts: fix to avoid some checks to be skipped.
  cnf-certification-test/lifecycle/podsets/podsets.go
  cnf-certification-test/lifecycle/suite.go
  generated_policy.json
  pkg/testhelper/testhelper.go
Labels: non backward compatible, ginkgoless

#1664 Load the checks' database using a standard function instead of init()
  cnf-certification-test/accesscontrol/suite.go
  cnf-certification-test/certification/suite.go
  cnf-certification-test/lifecycle/suite.go
  cnf-certification-test/manageability/suite.go
  cnf-certification-test/networking/suite.go
  cnf-certification-test/observability/suite.go
  cnf-certification-test/performance/suite.go
  main.go
  pkg/certsuite/certsuite.go
Labels: ginkgoless

#1667 Remove gotools; adjust expected/actual
  cmd/tnf/claim/compare/compare_test.go
  cmd/tnf/claim/compare/testcases/testcases_test.go
  cmd/tnf/claim/show/failures/failures_test.go
  cmd/tnf/pkg/claim/claim_test.go
  go.mod
  pkg/junit/convert_test.go
  pkg/scheduling/scheduling_test.go
Labels: ginkgoless

#1668 Graceful exit when no kubeconfig is configured
  internal/clientsholder/clientsholder.go
  main.go
Labels: ginkgoless

#1658 Transition platform-alteration suite to ginkgoless.
  cnf-certification-test/platform/suite.go
  generated_policy.json
  pkg/certsuite/certsuite.go
  pkg/testhelper/testhelper.go
Labels: ginkgoless

#1666 Switch to 1-to-1 TestID to Result struct
  .github/workflows/pre-main.yaml
  cmd/tnf/claim/compare/testcases/testcases.go
  cmd/tnf/claim/compare/testcases/testcases_test.go
  cmd/tnf/claim/compare/testdata/claim_access_control.json
  cmd/tnf/claim/compare/testdata/claim_observability.json
  cmd/tnf/claim/show/csv/csv.go
  cmd/tnf/claim/show/failures/failures.go
  cmd/tnf/claim/show/failures/failures_test.go
  cmd/tnf/claim/show/failures/testdata/claim1.json
  cmd/tnf/claim/show/failures/testdata/claim2.json
  cmd/tnf/pkg/claim/claim.go
  cmd/tnf/pkg/claim/claim_test.go
  pkg/checksdb/checksdb.go
  version.json
Labels: ginkgoless
