Repository redhat-best-practices-for-k8s/certsuite, pull requests merged in 2023-12, with the labels that each got.

#1663 log: add new log package that uses slog as global logger
  .gitignore
  Makefile
  cnf-certification-test/observability/suite.go
  internal/log/custom_handler.go
  internal/log/log.go
  internal/log/multi_handler.go
  main.go
  pkg/checksdb/check.go
Labels: ginkgoless

#1687 Bugfix: skip execution of remaining checks on error/panic.
  pkg/checksdb/checksgroup.go
Labels: ginkgoless

#1679 Remove ginkgo.AbortSuite
  cnf-certification-test/lifecycle/podrecreation/podrecreation.go
  cnf-certification-test/lifecycle/suite.go
  pkg/checksdb/check.go
  pkg/checksdb/checksdb.go
  pkg/checksdb/checksgroup.go
Labels: work in progress

#1691 Add JUnit XML output
  docs/configuration.md
  docs/test-output.md
  internal/formatters/formatters.go
  pkg/certsuite/certsuite.go
  pkg/checksdb/checksdb.go
  pkg/checksdb/parser.go
  pkg/checksdb/parser_test.go
  pkg/claimhelper/claimhelper.go
  pkg/claimhelper/claimhelper_test.go
  pkg/configuration/configuration.go
  script/run-container.sh
Labels: ginkgoless

#1701 Switch skip for nodePort test
  cnf-certification-test/accesscontrol/suite.go
Labels: ginkgoless

#1702 Remove early return with empty objects
  cnf-certification-test/accesscontrol/suite.go
Labels: ginkgoless

#1696 Move flags processing to run function
  cnf-certification-test/webserver/webserver.go
  main.go
  pkg/certsuite/certsuite.go
  pkg/flags/flags.go
Labels: ginkgoless

#1662 webserver: add tests as a table allowing the user to select an option
  cnf-certification-test/webserver/index.html
  cnf-certification-test/webserver/index.js
  cnf-certification-test/webserver/submit.js
  cnf-certification-test/webserver/toast.js
  cnf-certification-test/webserver/webserver.go
Labels: ginkgoless

#1711 log: set the configured log level to multiloggers
  internal/log/log.go
Labels: ginkgoless

#1698 Rename poststart test
  CATALOG.md
  cnf-certification-test/identifiers/doclinks.go
  cnf-certification-test/identifiers/identifiers.go
  cnf-certification-test/identifiers/remediation.go
  cnf-certification-test/lifecycle/suite.go
  generated_policy.json
Labels: ginkgoless

#1716 testhelper: remove unused functions
  pkg/testhelper/testhelper.go
  pkg/testhelper/testhelper_test.go
Labels: ginkgoless

#1713 Non graceful abort for unrecoverable/critical failures inside checkFn.
  cnf-certification-test/lifecycle/podrecreation/podrecreation.go
  internal/cli/cli.go
  pkg/checksdb/check.go
  pkg/checksdb/checksdb.go
  pkg/checksdb/checksgroup.go
Labels: ginkgoless

#1717 Remove early return in networking suite
  cnf-certification-test/networking/suite.go
Labels: ginkgoless

#1719 Consolidate checksGroup.Add calls
  cnf-certification-test/certification/suite.go
  cnf-certification-test/observability/suite.go
  cnf-certification-test/operator/suite.go
  cnf-certification-test/performance/suite.go
  cnf-certification-test/platform/suite.go
  cnf-certification-test/preflight/suite.go
Labels: ginkgoless

#1721 log: remove loghelper package
  cnf-certification-test/accesscontrol/namespace/namespace.go
  cnf-certification-test/accesscontrol/namespace/namespace_test.go
  cnf-certification-test/accesscontrol/suite.go
  cnf-certification-test/lifecycle/podsets/podsets.go
  cnf-certification-test/lifecycle/suite.go
  cnf-certification-test/networking/icmp/icmp.go
  cnf-certification-test/networking/icmp/icmp_test.go
  cnf-certification-test/networking/suite.go
  cnf-certification-test/platform/bootparams/bootparams.go
  cnf-certification-test/platform/suite.go
  internal/log/custom_handler.go
  internal/log/log.go
  main.go
  pkg/checksdb/check.go
  pkg/loghelper/loghelper.go
  pkg/loghelper/loghelper_test.go
Labels: ginkgoless

#1726 flags: change "claimloc" for "output-dir"
  main.go
  pkg/flags/flags.go
  run-cnf-suites.sh
Labels: ginkgoless

#1739 Merge branch 'main' into ginkgo_removal
  .github/actions/setup/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/merge.yaml
  .github/workflows/pre-main.yaml
  .github/workflows/preflight.yml
  .github/workflows/qe-hosted.yml
  .github/workflows/update-rhcos-mapping.yml
  CATALOG.md
  COMMITMENT
  Dockerfile
  Makefile
  cmd/tnf/claim/show/csv/cnf-type.json
  cmd/tnf/claim/show/csv/csv.go
  cmd/tnf/pkg/claim/claim.go
  cnf-certification-test/accesscontrol/suite.go
  cnf-certification-test/identifiers/doclinks.go
  cnf-certification-test/identifiers/identifiers.go
  cnf-certification-test/lifecycle/podrecreation/podrecreation.go
  cnf-certification-test/platform/bootparams/bootparams.go
  cnf-certification-test/platform/operatingsystem/files/rhcos_version_map
  docs/runtime-env.md
  docs/test-container.md
  go.mod
  go.sum
  internal/clientsholder/clientsholder.go
  pkg/diagnostics/diagnostics.go
  pkg/provider/pods.go
  pkg/provider/pods_test.go
  pkg/provider/provider.go
  pkg/provider/provider_test.go
  run-basic-batch-operators-test.sh
  version.json
Labels: ginkgoless

#1745 CLI output improvements: check's elapsed time and last log trace.
  cnf-certification-test/accesscontrol/suite.go
  internal/cli/cli.go
  internal/log/log.go
  pkg/certsuite/certsuite.go
  pkg/checksdb/check.go
  pkg/checksdb/checksgroup.go
  pkg/provider/pods.go
Labels: ginkgoless

#1750 CLI output: non-tty mode improvements.
  internal/cli/cli.go
Labels: ginkgoless

#1748 Enable QE PR tests
  .github/workflows/qe-hosted.yml
Labels: work in progress, ginkgoless

#1755 give precedence to the KUBECONFIG variable instead of the $HOME/.kube/config kubeconfig
  pkg/certsuite/certsuite.go
Labels: ginkgoless

#1753 Adjust location of the XML output file
  pkg/certsuite/certsuite.go
  pkg/claimhelper/claimhelper.go
Labels: ginkgoless

#1756 cli: fix typo in skip reason
  pkg/certsuite/certsuite.go
  pkg/checksdb/check.go
  pkg/checksdb/checksgroup.go
Labels: ginkgoless

#1759 Adjust XML output
  pkg/claimhelper/claimhelper.go
  pkg/claimhelper/claimhelper_test.go
  pkg/flags/flags_test.go
Labels: work in progress
